#!/bin/sh
cd "$(dirname "$0")"

docker run --rm -it \
    --name "neko_rooms" \
    -p "8080:8080" \
    -v "${PWD}/../:/app" \
    -e 'DOCKER_API_VERSION=1.39' \
	-e "NEKO_ROOMS_EPR=59000-59049" \
	-e "NEKO_ROOMS_NAT1TO1=192.168.1.20" \
	-e "NEKO_ROOMS_TRAEFIK_DOMAIN=neko-rooms.server.lan" \
	-e "NEKO_ROOMS_TRAEFIK_ENTRYPOINT=web" \
	-e "NEKO_ROOMS_TRAEFIK_NETWORK=traefik" \
    -v "/var/run/docker.sock:/var/run/docker.sock" \
    --entrypoint="/app/bin/neko_rooms" \
    neko_rooms_img serve --bind :8080;
